# Generated by Django 3.2.13 on 2022-08-07 10:24

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220802_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=mapbox_location_field.models.LocationField(default='(51.45629072,-0.631764294)', map_attrs={'center': (51.237738, -0.776037), 'readonly': False, 'style': 'mapbox://styles/mapbox/streets-v11'}, null=True),
        ),
    ]
