# Generated by Django 3.2.13 on 2022-08-09 12:51

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=mapbox_location_field.models.LocationField(default='(-0.631764294,51.45629072)', map_attrs={'center': (-0.631764294, 51.237738), 'readonly': False, 'style': 'mapbox://styles/mapbox/streets-v11'}, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
